env:
  global:
    - CC_TEST_REPORTER_ID=01f3b317eaae42803f6fc26db8de551dab0aada715f31df05004aca212272773
  secure: J4XliOpawW4EQPIdROoZeiP2hajCMjkxbOWjyiWf23T8lrtn9uGiAn7NqWn1H0t472RLhtlR2pOBNjpRUgnUoP1o5ZO3OyegPYq2tPAwvcZEd44pT+5WlvdR9evaIs3Rk5B4lhlwQKs7YDLeh4HwKyJiF3o7K0bX7OtAkHrWWSJ2QJJVbCl/CKVw5lU5s47qDhQlV2JFUkBXFKCa98/7HWrTrYjvnVyjM6OCufr8dPvmGxBv2xvoC7tXMGzZTsBJvqv9Fm20aqTAph/7EdpukrRQpkTU0qTfnK2J4q3yV3rMqlT1iT/hTe/eWfw5t4q/hDQzQt+T5YujbTcD4UCV1XpbGNdKKNoGqBbM8M9zgrUjqlFNC+6ANYTBoYNF7LkBTZmwDgxUdDeQvCrzTzjazsUlmtZMB9d7q6i4RDOSpV0SPuhRtQa2s7DoKCO9BNJd8F9HNcsIPWFDF12n6l/xruaWBVXMvP/mG/QIleRpSCt/serstOOybG5JuTshlZY0+012fl/K575a7xOaGN86FPa/a4+RXnxI1WodhvNreB/5GKmU3fWJ9q8pE+THnlgQb/N9EkKr1/G88x2TwswfQTkNnKFzw8QtWLZyDPKU3HAUWTwS6hyrsN+GupTtFASmD5gBUah6h86+15H1hz4FjhaqIfQlYxJHvItcF2DDZss=
language: ruby
cache:
- bundler
- yarn
services:
- postgresql
before_install:
- nvm install --lts
install:
  - bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}
  - npm install   
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
- bundle install --jobs=3 --retry=3
- yarn
- bundle exec rake db:create
- bundle exec rake db:schema:load
script:
- bundle exec cucumber
after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT