test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon_dev:
  service: S3
  access_key_id: <%= Rails.application.credentials.config[:AWS_S3_KEY] %>
  secret_access_key: <%= Rails.application.credentials.config[:AWS_S3_SECRET_KEY] %>
  region: us-west-1
  bucket: nanoframe-website-dev

amazon_prod:
  service: S3
  access_key_id: <%= Rails.application.credentials.config[:AWS_S3_KEY] %>
  secret_access_key: <%= Rails.application.credentials.config[:AWS_S3_SECRET_KEY] %>
  region: us-west-1
  bucket: nanoframe-website-pro
