name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCTR: ./cc-test-reporter
      TZ: America/Los_Angeles
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        id: ruby_version
      - name: Install external dependencies
        run: |
          sudo apt-get install libmagic-dev
          sudo apt-get install coinor-libcbc-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.3"
          bundler-cache: true
      - name: Get NodeJS version
        run: echo "::set-output name=NODE_VERSION::$(cat .node-version)"
        id: node_version
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.node_version.outputs.NODE_VERSION }}"
      - name: Set up Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Set up PostgreSQL
        run: |
          sudo apt-get install postgresql libpq-dev
          sudo service postgresql start
          sudo -u postgres createuser --superuser "$USER"
      - name: Set up test database
        run: bundle exec rake db:setup
      - name: Run tests
        run: |
          bundle exec rake spec
          ./cc-test-reporter format-coverage --input-type simplecov --output coverage/codeclimate.$SUITE.json "/home/runner/work/nanoframe/nanoframe/coverage/.resultset.json" 
      - name: Publish code coverage
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
          ./cc-test-reporter upload-coverage --id ${{ secrets.CC_TEST_REPORTER_ID }}
          ./cc-test-reporter after-build --id ${{ secrets.CC_TEST_REPORTER_ID }}
