name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        id: ruby_version
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.0.x"
      - name: Get NodeJS version
        run: echo "::set-output name=NODE_VERSION::$(cat .node-version)"
        id: node_version
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.node_version.outputs.NODE_VERSION }}"
      - name: Set up PostgreSQL
        run: |
          sudo apt-get install postgresql libpq-dev
          sudo service postgresql start
          sudo -u postgres createuser --superuser "$USER"
      - name: Install Dependencies
        run: |
          sudo apt-get install libmagic-dev
          sudo apt-get install coinor-libcbc-dev
          bundle install
      - name: Set up test database
        run: bundle exec rake db:setup
      - name: Run tests
        run: |
          bundle exec rake spec
          ./cc-test-reporter format-coverage --output coverage/codeclimate.$SUITE.json --input-type simplecov
      - name: Publish code coverage
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
          ./cc-test-reporter upload-coverage --id ${{ secrets.CC_TEST_REPORTER_ID }}
          ./cc-test-reporter after-build --id ${{ secrets.CC_TEST_REPORTER_ID }}
