name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        id: ruby_version
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.0.x"
      - name: Get NodeJS version
        run: echo "::set-output name=NODE_VERSION::$(cat .node-version)"
        id: node_version
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.node_version.outputs.NODE_VERSION }}"
      - name: Set up PostgreSQL
        run: |
          sudo apt-get install postgresql libpq-dev
          sudo service postgresql start
          sudo -u postgres createuser --superuser "$USER"
      - name: Install Dependencies
        run: bundle install
      - name: Set up test database
        run: bundle exec rake db:setup
      - name: Run tests
        run: bundle exec rake spec
  coverage:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: npm install -g yarn
      - run: yarn install
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 01f3b317eaae42803f6fc26db8de551dab0aada715f31df05004aca212272773
        with:
          coverageCommand: bundle exec rake spec
          coverageLocations: |
            ${{github.workspace}}/coverage/.last_run.json
